version: '3.8'

services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Teams
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=Teams
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
